# action.yml
name: 'Issue duplicate detector'
description: "Finds duplicate issues using NLP (semantic similarity) and adds a label/comment."

branding:
  icon: 'search'
  color: 'blue'

inputs:
  github-token:
    description: 'The GITHUB_TOKEN for the repository using this action. Required to interact with the GitHub API.'
    required: true
  
  threshold:
    description: 'The minimum similarity score (between 0.0 and 1.0) to consider an issue a duplicate.'
    required: false
    default: '0.80'

  duplicate-label:
    description: 'The name of the label to add to issues identified as potential duplicates. The label must exist in the repository.'
    required: false
    default: 'potential-duplicate'


runs:
  using: 'docker'
  image: 'Dockerfile'